---
 - hosts: all
   tasks:
   - name: pull the image from DOcker registry
     raw: docker pull kanduriprasanth/project2

   - name: remove existing container if already exists
     raw: docker rm -f app
     ignore_errors: true

   - name:  spin the container
     raw: docker run -dti --name app -p 71:80 kanduriprasanth/project2 /bin/bash
...

